### ISSUE TITLE
require electron-reload ?

### ISSUE THREAD

**Issue by NNemec** [DenisVuyka/ng2-electron#3]
Thanks for this repo. As a newcomer to the angular/electron world, this is exactly what I was looking for.

Have you seen https://www.npmjs.com/package/electron-reload ? For me, this adds the last bit of comfort that I was missing with electron when coming from angular web development.

**Comment by DenisVuyka** [comment]
Thanks for suggestion. I will introduce this bit after holidays.

**Comment by DenisVuyka** [comment]
I'll leave this for template users to implement if really needed.
