### ISSUE TITLE
ng statements in html

### ISSUE THREAD

**Issue by angulardev23** [DenisVuyka/ng2-electron#9]
Hi,
I downloaded and installed this app and it works fine.
I try to to use ng statements in html file and it doesn't work. "ng-if" for example.
Do u know how to set up the application to do it?

**Comment by DenisVuyka** [comment]
There’s no “no-if” in Angular 2 and later (or just Angular). Please refer to Angular docs for more details

**Comment by angulardev23** [comment]
ng-repeat="dashboard in dashboards track by $index" 
something like this. I mean all ng statements in html file don't work. BTW and u wrote "no-if" and yeah there is no such a thing like this

**Comment by DenisVuyka** [comment]
@angulardev23 despite the typo I'm afraid the answer is still valid - please refer to this article https://angular.io/docs
